# Generated by Django 3.0.3 on 2020-10-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
